linters:
  enable-all: false
  disable-all: true
  fast: false
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - gofumpt

issues:
  exclude-rules:
    - path: authenticator_test.go
      linters:
        - bodyclose
        - unparam
    - path: parser_test.go
      linters:
        - lll
    - path: signatureheader_test.go
      linters:
        - lll
run:
  timeout: 3m
